#!/usr/bin/env bash
# Deploy the full Agenttic stack (app + Postgres + Redis) to a remote host over
# SSH. Idempotent: re-running redeploys the current tree and preserves the
# generated admin token + any Anthropic key already on the host.
#
#   ./scripts/deploy.sh [ssh-host]          # default host: node1
#
# Safe by default: the app port binds to 127.0.0.1 on the remote host (NOT the
# public IP) — front it with TLS (Caddy/nginx/ingress) before exposing it.
# To bind publicly anyway (authenticated but plaintext — discouraged):
#   ASCORE_BIND=0.0.0.0 ./scripts/deploy.sh node1
set -euo pipefail

HOST="${1:-node1}"
REMOTE_DIR="${REMOTE_DIR:-/opt/agenttic}"
BIND="${ASCORE_BIND:-127.0.0.1}"
PORT="${ASCORE_PORT:-8700}"
LOCAL_DIR="$(cd "$(dirname "$0")/.." && pwd)"

say() { printf '\n\033[1;36m== %s\033[0m\n' "$*"; }

say "1/7  Check SSH to $HOST"
ssh -o BatchMode=yes -o ConnectTimeout=15 "$HOST" 'echo ok' >/dev/null || {
  echo "ERROR: cannot ssh $HOST non-interactively. Authorize your key first."; exit 1; }

say "2/7  Install Docker Engine + compose plugin (detect distro)"
ssh "$HOST" 'bash -se' <<'REMOTE'
set -euo pipefail
if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
  echo "Docker + compose already present: $(docker --version)"
else
  . /etc/os-release
  echo "Distro: $ID $VERSION_ID — installing Docker via get.docker.com"
  curl -fsSL https://get.docker.com | sudo sh
fi
# add the login user to the docker group (effective on next login/session)
sudo usermod -aG docker "$USER" || true
sudo systemctl enable --now docker || true
REMOTE

say "3/7  Sync repo -> $HOST:$REMOTE_DIR"
ssh "$HOST" "sudo mkdir -p $REMOTE_DIR && sudo chown \$USER $REMOTE_DIR"
rsync -az --delete \
  --exclude '.git' --exclude '.venv' --exclude 'node_modules' \
  --exclude 'ui/dist' --exclude '__pycache__' --exclude '.pytest_cache' \
  --exclude '*.db' --exclude '*.db-wal' --exclude '*.db-shm' \
  --exclude 'backups' --exclude 'uploads' --exclude '.env' \
  -e ssh "$LOCAL_DIR/" "$HOST:$REMOTE_DIR/"

say "4/7  Compose override (port bind + service ordering) + config"
ssh "$HOST" "bash -se -- '$REMOTE_DIR' '$BIND' '$PORT'" <<'REMOTE'
set -euo pipefail
DIR="$1"; BIND="$2"; PORT="$3"; cd "$DIR"
cp -f config.prod.yaml config.yaml          # the mounted /app/config.yaml
cat > docker-compose.override.yml <<YAML
services:
  app:
    ports: ["$BIND:$PORT:8700"]            # default 127.0.0.1 — front with TLS to expose
    depends_on:
      postgres: {condition: service_healthy}
      redis: {condition: service_healthy}
YAML
echo "App will bind ${BIND}:${PORT} on the host."
REMOTE

say "5/7  Secrets -> $HOST:$REMOTE_DIR/.env  (never committed)"
ssh "$HOST" "bash -se -- '$REMOTE_DIR'" <<'REMOTE'
set -euo pipefail
DIR="$1"; cd "$DIR"; touch .env; chmod 600 .env
get() { grep -E "^$1=" .env 2>/dev/null | tail -1 | cut -d= -f2-; }

# admin token: preserve across redeploys, else generate a strong one
TOKEN="$(get ASCORE_API_TOKEN)"; [ -n "$TOKEN" ] || TOKEN="$(openssl rand -hex 32)"

# Anthropic key: reuse .env, else the host env, else leave a clear placeholder
AKEY="$(get ANTHROPIC_API_KEY)"; [ -n "$AKEY" ] && [ "$AKEY" != "REPLACE_ME" ] || AKEY="${ANTHROPIC_API_KEY:-REPLACE_ME}"

cat > .env <<ENV
# generated by deploy.sh — DO NOT COMMIT
ASCORE_API_TOKEN=$TOKEN
ANTHROPIC_API_KEY=$AKEY
ASCORE_DB=postgresql+psycopg://ascore:ascore@postgres:5432/ascore
ASCORE_REDIS_URL=redis://redis:6379/0
ENV
echo "Wrote .env (token preserved/generated; ANTHROPIC_API_KEY=$([ "$AKEY" = REPLACE_ME ] && echo MISSING || echo set))"
REMOTE

say "6/7  Bring up Postgres + Redis, run migrations, then the app"
ssh "$HOST" "bash -se -- '$REMOTE_DIR'" <<'REMOTE'
set -euo pipefail
DIR="$1"; cd "$DIR"
dc() { docker compose --profile postgres --profile redis "$@"; }
sg docker -c "cd $DIR && docker compose --profile postgres --profile redis up -d --wait postgres redis" \
  || dc up -d --wait postgres redis
# run migrations against Postgres as a one-off (app also self-migrates on boot)
sg docker -c "cd $DIR && docker compose run --rm app ascore migrate --config /app/config.yaml" \
  || dc run --rm app ascore migrate --config /app/config.yaml
sg docker -c "cd $DIR && docker compose --profile postgres --profile redis up -d --wait app" \
  || dc up -d --wait app
docker compose ps || sg docker -c "cd $DIR && docker compose ps"
REMOTE

say "7/7  Verify /health and /ready"
ssh "$HOST" "bash -se -- '$BIND' '$PORT'" <<'REMOTE'
set -euo pipefail
BIND="$1"; PORT="$2"; H="http://127.0.0.1:$PORT"
for ep in health ready; do
  printf '%s -> ' "$ep"; curl -fsS "$H/$ep" && echo || echo "FAILED"
done
echo "Listening:"; ss -ltnp 2>/dev/null | grep ":$PORT" || true
REMOTE

say "Done. Admin token is in $HOST:$REMOTE_DIR/.env (ASCORE_API_TOKEN)."
echo "Access (from the host / behind your tunnel or TLS proxy): http://127.0.0.1:$PORT"
echo "If ANTHROPIC_API_KEY shows MISSING, set it in $REMOTE_DIR/.env and: docker compose up -d app"
